More lint fixes

diff --git a/.github/workflows/ok-to-test-command.yml b/.github/workflows/ok-to-test-command.yml
--- a/.github/workflows/ok-to-test-command.yml
+++ b/.github/workflows/ok-to-test-command.yml
@@ -1,3 +1,4 @@
+---
 name: Integration Test cases
 on:
   pull_request:
@@ -10,14 +11,14 @@ jobs:
     strategy:
       max-parallel: 1
       matrix:
-        python-version: ['3.9']
+        python-version: ["3.9"]
     if: github.event_name == 'repository_dispatch'
     steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
 
       - uses: actions/checkout@v2
         with:
-          ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
+          ref: refs/pull/${{ github.event.client_payload.pull_request.number }}/merge
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
@@ -65,23 +66,23 @@ jobs:
 
       - name: Code Coverage Check
         if: ${{ always() }}
-        run:  |
-              cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
-              ansible-test coverage html
-              sshpass -p '${{ secrets.FILER_PASSWORD }}' scp -r tests/output ${{ secrets.FILER_LOCATION }}
-              echo "Code coverage: Checking if code coverage is above threshold..."
-              export COVERAGE_THRESHOLD=70
-              echo "Threshold: $COVERAGE_THRESHOLD %"
-              totalCoverage=`grep TOTAL coverage.txt | awk '{print $6}' | sed 's/%//'`
-              echo "TOTAL_COVERAGE=${totalCoverage}" >> $GITHUB_ENV
-              echo "Current integration test coverage : $totalCoverage %"
-              if (( $(echo "$totalCoverage $COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-                  echo "Coverage passed"
-              else
-                  echo "Current integration test coverage is below threshold. Please add more integration tests or adjust threshold to a lower value."
-                  echo "Coverage check failed"
-                  exit 1
-              fi
+        run: |
+          cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
+          ansible-test coverage html
+          sshpass -p '${{ secrets.FILER_PASSWORD }}' scp -r tests/output ${{ secrets.FILER_LOCATION }}
+          echo "Code coverage: Checking if code coverage is above threshold..."
+          export COVERAGE_THRESHOLD=70
+          echo "Threshold: $COVERAGE_THRESHOLD %"
+          totalCoverage=`grep TOTAL coverage.txt | awk '{print $6}' | sed 's/%//'`
+          echo "TOTAL_COVERAGE=${totalCoverage}" >> $GITHUB_ENV
+          echo "Current integration test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "Coverage passed"
+          else
+              echo "Current integration test coverage is below threshold. Please add more integration tests or adjust threshold to a lower value."
+              echo "Coverage check failed"
+              exit 1
+          fi
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
 
diff --git a/.github/workflows/unit_testing.yml b/.github/workflows/unit_testing.yml
--- a/.github/workflows/unit_testing.yml
+++ b/.github/workflows/unit_testing.yml
@@ -1,3 +1,4 @@
+---
 name: Run compile and tests
 
 on:
@@ -12,7 +13,7 @@ jobs:
     runs-on: ubuntu-20.04
     strategy:
       matrix:
-        python-version: ['3.9']
+        python-version: ["3.9"]
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python ${{ matrix.python-version }}
@@ -41,7 +42,7 @@ jobs:
     runs-on: ubuntu-20.04
     strategy:
       matrix:
-        python-version: ['3.9']
+        python-version: ["3.9"]
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python ${{ matrix.python-version }}
@@ -68,18 +69,18 @@ jobs:
           ansible-test units --docker default --python ${{ matrix.python-version }} --coverage -v
           ansible-test coverage report --include */plugins/* --omit */utils.py,_fetch_url* > coverage.txt
       - name: Code Coverage Check
-        run:  |
-              cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
-              echo "Code coverage: Checking if code coverage is above threshold..."
-              export TESTCOV_THRESHOLD=55
-              echo "Threshold: $TESTCOV_THRESHOLD %"
-              totalCoverage=`grep TOTAL coverage.txt | awk '{print $6}' | sed 's/%//'`
-              echo "TOTAL_COVERAGE=${totalCoverage}" >> $GITHUB_ENV
-              echo "Current test coverage : $totalCoverage %"
-              if (( $(echo "$totalCoverage $TESTCOV_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-                  echo "Coverage passed"
-              else
-                  echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-                  echo "Coverage check failed"
-                  exit 1
-              fi
+        run: |
+          cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
+          echo "Code coverage: Checking if code coverage is above threshold..."
+          export TESTCOV_THRESHOLD=55
+          echo "Threshold: $TESTCOV_THRESHOLD %"
+          totalCoverage=`grep TOTAL coverage.txt | awk '{print $6}' | sed 's/%//'`
+          echo "TOTAL_COVERAGE=${totalCoverage}" >> $GITHUB_ENV
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TESTCOV_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "Coverage passed"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Coverage check failed"
+              exit 1
+          fi
