add negative tests to pipeline

diff --git a/.github/workflows/ok-to-test-command.yml b/.github/workflows/ok-to-test-command.yml
--- a/.github/workflows/ok-to-test-command.yml
+++ b/.github/workflows/ok-to-test-command.yml
@@ -95,12 +95,20 @@ jobs:
                   exit 1
               fi
               echo "===> Running inventory test (negative tests)..."
-              if ansible-playbook -i tests/integration/targets/inventory_test/inventory_test_negative_tests/nutanix.yml \
-              tests/integration/targets/inventory_test/inventory_test_negative_tests/inventory.yml \
+              if ansible-playbook -i tests/integration/targets/inventory_test/inventory_test_negative_test_1/nutanix.yml \
+              tests/integration/targets/inventory_test/inventory_test_negative_test_1/inventory.yml \
               2>&1 | tee -a test_output.log; then
-                  echo "Inventory test negative tests completed successfully."
+                  echo "Inventory test negative test 1 completed successfully."
               else
-                  echo "Inventory test negative tests failed. See logs above." | tee -a test_output.log
+                  echo "Inventory test negative test 1 failed. See logs above." | tee -a test_output.log
+                  exit 1
+              fi
+              if ansible-playbook -i tests/integration/targets/inventory_test/inventory_test_negative_test_2/nutanix.yml \
+              tests/integration/targets/inventory_test/inventory_test_negative_test_2/inventory.yml \
+              2>&1 | tee -a test_output.log; then
+                  echo "Inventory test negative test 2 completed successfully."
+              else
+                  echo "Inventory test negative test 2 failed. See logs above." | tee -a test_output.log
                   exit 1
               fi
           fi
