Sync main branch with 1.9.0, 1.9.1 and 1.9.2 releases from public repository. (#66)
Sync main branch
---------

Co-authored-by: Pradeepsingh Bhati <pradeep.bhati@nutanix.com>

---------

Co-authored-by: Gevorg Khachatryan <gevorg.khachatryan@nutanix.com>
Co-authored-by: alaa-bish <alaa.bishtawi@nutanix.com>
Co-authored-by: Gianluca Salvo <Gianlu@users.noreply.github.com>
Co-authored-by: Gianluca Salvo <gianluca.salvo@gruppomol.it>
Co-authored-by: Nathaniel Roberts <107402519+Nathaniel-Roberts@users.noreply.github.com>

diff --git a/.github/workflows/unit_testing.yml b/.github/workflows/unit_testing.yml
--- a/.github/workflows/unit_testing.yml
+++ b/.github/workflows/unit_testing.yml
@@ -1,3 +1,4 @@
+---
 name: Run compile and tests
 
 on:
@@ -8,11 +9,12 @@ on:
     branches:
       - main
 jobs:
-  sanity:
-    runs-on: ubuntu-latest
+  sanity1:
+    name: Sanity tests with ansible-core==2.15.0
+    runs-on: ubuntu-20.04
     strategy:
       matrix:
-        python-version: ['3.9']
+        python-version: ["3.9"]
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python ${{ matrix.python-version }}
@@ -20,7 +22,7 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
       - name: Setup Docker
-        uses: docker-practice/actions-setup-docker@v1
+        uses: docker-practice/actions-setup-docker@master
       - name: Install ansible
         run: |
           pip install -r requirements.txt
@@ -38,10 +40,10 @@ jobs:
           cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
           ansible-test sanity --docker default --python ${{ matrix.python-version }} -v
   unit_testing:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     strategy:
       matrix:
-        python-version: ['3.7', '3.8', '3.9']
+        python-version: ["3.9"]
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python ${{ matrix.python-version }}
@@ -49,7 +51,7 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
       - name: Setup Docker
-        uses: docker-practice/actions-setup-docker@v1
+        uses: docker-practice/actions-setup-docker@master
       - name: Install ansible
         run: |
           pip install -r requirements.txt
@@ -68,18 +70,18 @@ jobs:
           ansible-test units --docker default --python ${{ matrix.python-version }} --coverage -v
           ansible-test coverage report --include */plugins/* --omit */utils.py,_fetch_url* > coverage.txt
       - name: Code Coverage Check
-        run:  |
-              cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
-              echo "Code coverage: Checking if code coverage is above threshold..."
-              export TESTCOV_THRESHOLD=55
-              echo "Threshold: $TESTCOV_THRESHOLD %"
-              totalCoverage=`grep TOTAL coverage.txt | awk '{print $6}' | sed 's/%//'`
-              echo "TOTAL_COVERAGE=${totalCoverage}" >> $GITHUB_ENV
-              echo "Current test coverage : $totalCoverage %"
-              if (( $(echo "$totalCoverage $TESTCOV_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-                  echo "Coverage passed"
-              else
-                  echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-                  echo "Coverage check failed"
-                  exit 1
-              fi
+        run: |
+          cd /home/${USER}/.ansible/collections/ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
+          echo "Code coverage: Checking if code coverage is above threshold..."
+          export TESTCOV_THRESHOLD=55
+          echo "Threshold: $TESTCOV_THRESHOLD %"
+          totalCoverage=`grep TOTAL coverage.txt | awk '{print $6}' | sed 's/%//'`
+          echo "TOTAL_COVERAGE=${totalCoverage}" >> $GITHUB_ENV
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TESTCOV_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "Coverage passed"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Coverage check failed"
+              exit 1
+          fi
